In [59]:
import pandas as pd 
file_path = 'C:/Users/kashy/Downloads/Diabetes Missing Data.csv'
data = pd.read_csv(file_path)
data.head()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

In [57]:
null_values = data.isnull()
print(null_values)

     Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin    BMI  \
0       False    False         False      False           True  False
1       False    False         False      False           True  False
2       False    False         False       True           True  False
3       False    False         False      False          False  False
4       False    False         False      False          False  False
..        ...      ...           ...        ...            ...    ...
763     False    False         False      False          False  False
764     False    False         False      False           True  False
765     False    False         False      False          False  False
766     False    False         False       True           True  False
767     False    False         False      False           True  False

     Diabetes_Pedigree    Age  Class
0                False  False  False
1                False  False  False
2                False  False  False
3                False  False  False
4                False  False  False
..                 ...    ...    ...
763              False  False  False
764              False  False  False
765              False  False  False
766              False  False  False
767              False  False  False

[768 rows x 9 columns]

In [43]:
data.notnull()

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,True,True,True,True,False,True,True,True,True
1,True,True,True,True,False,True,True,True,True
2,True,True,True,False,False,True,True,True,True
3,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...
763,True,True,True,True,True,True,True,True,True
764,True,True,True,True,False,True,True,True,True
765,True,True,True,True,True,True,True,True,True
766,True,True,True,False,False,True,True,True,True
767,True,True,True,True,False,True,True,True,True

In [45]:
data.isnull().sum()

Pregnant               0
Glucose                5
Diastolic_BP          35
Skin_Fold            227
Serum_Insulin        374
BMI                   11
Diabetes_Pedigree      0
Age                    0
Class                  0
dtype: int64

In [47]:
data.fillna(0)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,6,148.0,72.0,35.0,0.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,0.0,26.6,0.351,31,0
2,8,183.0,64.0,0.0,0.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63,0
764,2,122.0,70.0,27.0,0.0,36.8,0.340,27,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30,0
766,1,126.0,60.0,0.0,0.0,30.1,0.349,47,1
767,1,93.0,70.0,31.0,0.0,30.4,0.315,23,0

In [71]:
data.isnull().head(5)

,Pregnant,Glucose,Diastolic_BP,Skin_Fold,Serum_Insulin,BMI,Diabetes_Pedigree,Age,Class
0,False,False,False,False,True,False,False,False,False
1,False,False,False,False,True,False,False,False,False
2,False,False,False,True,True,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False

In [63]:
top_10_rows = data.head(10)
null_values_top_10 = top_10_rows.isnull()
print(null_values_top_10)

   Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin    BMI  \
0     False    False         False      False           True  False
1     False    False         False      False           True  False
2     False    False         False       True           True  False
3     False    False         False      False          False  False
4     False    False         False      False          False  False
5     False    False         False       True           True  False
6     False    False         False      False          False  False
7     False    False          True       True           True  False
8     False    False         False      False          False  False
9     False    False         False       True           True   True

   Diabetes_Pedigree    Age  Class
0              False  False  False
1              False  False  False
2              False  False  False
3              False  False  False
4              False  False  False
5              False  False  False
6              False  False  False
7              False  False  False
8              False  False  False
9              False  False  False

In [65]:
null_values_count_top_10 = null_values_top_10.sum()
print(null_values_count_top_10)

Pregnant             0
Glucose              0
Diastolic_BP         1
Skin_Fold            4
Serum_Insulin        6
BMI                  1
Diabetes_Pedigree    0
Age                  0
Class                0
dtype: int64

In [69]:
bottom_10_rows = data.tail(10)
null_values_bottom_10 = bottom_10_rows.isnull()
print(null_values_bottom_10)

     Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin    BMI  \
758     False    False         False       True           True  False
759     False    False         False       True           True  False
760     False    False         False      False          False  False
761     False    False         False      False           True  False
762     False    False         False       True           True  False
763     False    False         False      False          False  False
764     False    False         False      False           True  False
765     False    False         False      False          False  False
766     False    False         False       True           True  False
767     False    False         False      False           True  False

     Diabetes_Pedigree    Age  Class
758              False  False  False
759              False  False  False
760              False  False  False
761              False  False  False
762              False  False  False
763              False  False  False
764              False  False  False
765              False  False  False
766              False  False  False
767              False  False  False

In [73]:
filled_with_0 = top_10_rows.fillna(0)
print(filled_with_0)

   Pregnant  Glucose  Diastolic_BP  Skin_Fold  Serum_Insulin   BMI  \
0         6    148.0          72.0       35.0            0.0  33.6
1         1     85.0          66.0       29.0            0.0  26.6
2         8    183.0          64.0        0.0            0.0  23.3
3         1     89.0          66.0       23.0           94.0  28.1
4         0    137.0          40.0       35.0          168.0  43.1
5         5    116.0          74.0        0.0            0.0  25.6
6         3     78.0          50.0       32.0           88.0  31.0
7        10    115.0           0.0        0.0            0.0  35.3
8         2    197.0          70.0       45.0          543.0  30.5
9         8    125.0          96.0        0.0            0.0   0.0

   Diabetes_Pedigree  Age  Class
0              0.627   50      1
1              0.351   31      0
2              0.672   32      1
3              0.167   21      0
4              2.288   33      1
5              0.201   30      0
6              0.248   26      1
7              0.134   29      0
8              0.158   53      1
9              0.232   54      1

In [83]:
data["Skin_Fold"].fillna("No skinfold", inplace = True)
print(data)

     Pregnant  Glucose  Diastolic_BP     Skin_Fold  Serum_Insulin   BMI  \
0           6    148.0          72.0          35.0            NaN  33.6
1           1     85.0          66.0          29.0            NaN  26.6
2           8    183.0          64.0  No skin_fold            NaN  23.3
3           1     89.0          66.0          23.0           94.0  28.1
4           0    137.0          40.0          35.0          168.0  43.1
..        ...      ...           ...           ...            ...   ...
763        10    101.0          76.0          48.0          180.0  32.9
764         2    122.0          70.0          27.0            NaN  36.8
765         5    121.0          72.0          23.0          112.0  26.2
766         1    126.0          60.0  No skin_fold            NaN  30.1
767         1     93.0          70.0          31.0            NaN  30.4

     Diabetes_Pedigree  Age  Class
0                0.627   50      1
1                0.351   31      0
2                0.672   32      1
3                0.167   21      0
4                2.288   33      1
..                 ...  ...    ...
763              0.171   63      0
764              0.340   27      0
765              0.245   30      0
766              0.349   47      1
767              0.315   23      0

[768 rows x 9 columns]

In [99]:
data.fillna('bfill')
data["Serum_Insulin"].fillna("No Insulin", inplace = True)
print(data)

     Pregnant  Glucose  Diastolic_BP     Skin_Fold Serum_Insulin   BMI  \
0           6    148.0          72.0          35.0    No Insulin  33.6
1           1     85.0          66.0          29.0    No Insulin  26.6
2           8    183.0          64.0  No skin_fold    No Insulin  23.3
3           1     89.0          66.0          23.0          94.0  28.1
4           0    137.0          40.0          35.0         168.0  43.1
..        ...      ...           ...           ...           ...   ...
763        10    101.0          76.0          48.0         180.0  32.9
764         2    122.0          70.0          27.0    No Insulin  36.8
765         5    121.0          72.0          23.0         112.0  26.2
766         1    126.0          60.0  No skin_fold    No Insulin  30.1
767         1     93.0          70.0          31.0    No Insulin  30.4

     Diabetes_Pedigree  Age  Class
0                0.627   50      1
1                0.351   31      0
2                0.672   32      1
3                0.167   21      0
4                2.288   33      1
..                 ...  ...    ...
763              0.171   63      0
764              0.340   27      0
765              0.245   30      0
766              0.349   47      1
767              0.315   23      0

[768 rows x 9 columns]

In [97]:
data.fillna('backfill')
data["Serum_Insulin"].fillna("No Insulin", inplace = True)
print(data)

     Pregnant  Glucose  Diastolic_BP     Skin_Fold Serum_Insulin   BMI  \
0           6    148.0          72.0          35.0    No Insulin  33.6
1           1     85.0          66.0          29.0    No Insulin  26.6
2           8    183.0          64.0  No skin_fold    No Insulin  23.3
3           1     89.0          66.0          23.0          94.0  28.1
4           0    137.0          40.0          35.0         168.0  43.1
..        ...      ...           ...           ...           ...   ...
763        10    101.0          76.0          48.0         180.0  32.9
764         2    122.0          70.0          27.0    No Insulin  36.8
765         5    121.0          72.0          23.0         112.0  26.2
766         1    126.0          60.0  No skin_fold    No Insulin  30.1
767         1     93.0          70.0          31.0    No Insulin  30.4

     Diabetes_Pedigree  Age  Class
0                0.627   50      1
1                0.351   31      0
2                0.672   32      1
3                0.167   21      0
4                2.288   33      1
..                 ...  ...    ...
763              0.171   63      0
764              0.340   27      0
765              0.245   30      0
766              0.349   47      1
767              0.315   23      0

[768 rows x 9 columns]

In [95]:
data.fillna('pad')
data["Serum_Insulin"].fillna("No Insulin", inplace = True)
print(data)

     Pregnant  Glucose  Diastolic_BP     Skin_Fold Serum_Insulin   BMI  \
0           6    148.0          72.0          35.0    No Insulin  33.6
1           1     85.0          66.0          29.0    No Insulin  26.6
2           8    183.0          64.0  No skin_fold    No Insulin  23.3
3           1     89.0          66.0          23.0          94.0  28.1
4           0    137.0          40.0          35.0         168.0  43.1
..        ...      ...           ...           ...           ...   ...
763        10    101.0          76.0          48.0         180.0  32.9
764         2    122.0          70.0          27.0    No Insulin  36.8
765         5    121.0          72.0          23.0         112.0  26.2
766         1    126.0          60.0  No skin_fold    No Insulin  30.1
767         1     93.0          70.0          31.0    No Insulin  30.4

     Diabetes_Pedigree  Age  Class
0                0.627   50      1
1                0.351   31      0
2                0.672   32      1
3                0.167   21      0
4                2.288   33      1
..                 ...  ...    ...
763              0.171   63      0
764              0.340   27      0
765              0.245   30      0
766              0.349   47      1
767              0.315   23      0

[768 rows x 9 columns]

In [93]:
data.fillna('ffill')
data["Serum_Insulin"].fillna("No Insulin", inplace = True)
print(data)

     Pregnant  Glucose  Diastolic_BP     Skin_Fold Serum_Insulin   BMI  \
0           6    148.0          72.0          35.0    No Insulin  33.6
1           1     85.0          66.0          29.0    No Insulin  26.6
2           8    183.0          64.0  No skin_fold    No Insulin  23.3
3           1     89.0          66.0          23.0          94.0  28.1
4           0    137.0          40.0          35.0         168.0  43.1
..        ...      ...           ...           ...           ...   ...
763        10    101.0          76.0          48.0         180.0  32.9
764         2    122.0          70.0          27.0    No Insulin  36.8
765         5    121.0          72.0          23.0         112.0  26.2
766         1    126.0          60.0  No skin_fold    No Insulin  30.1
767         1     93.0          70.0          31.0    No Insulin  30.4

     Diabetes_Pedigree  Age  Class
0                0.627   50      1
1                0.351   31      0
2                0.672   32      1
3                0.167   21      0
4                2.288   33      1
..                 ...  ...    ...
763              0.171   63      0
764              0.340   27      0
765              0.245   30      0
766              0.349   47      1
767              0.315   23      0

[768 rows x 9 columns]